// Generated by CoffeeScript 1.8.0
(function() {
  var Bettle, formatRequires, replaceDefine, splitStr;

  replaceDefine = require('./define/replace');

  formatRequires = require('./define/format');

  splitStr = '\n';

  Bettle = function(fileStr) {
    return this.translateFileStringToList(fileStr);
  };

  Bettle.prototype = {
    fileList: [],
    translateFileStringToList: function(fileStr) {
      if (fileStr) {
        fileStr = fileStr + "";
        this.fileList = fileStr.split(splitStr);
      }
      return this;
    },
    replaceDefine: function(options) {
      this.fileList = replaceDefine(this.fileList, options);
      return this;
    },
    formatRequires: function(options) {
      this.fileList = formatRequires(this.fileList, options);
      return this;
    },
    getFileString: function() {
      return this.fileList.join(splitStr);
    }
  };

  module.exports = Bettle;

}).call(this);
